# Generated by Django 3.0 on 2019-12-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=14, max_digits=20, null=True)),
                ('y', models.DecimalField(decimal_places=14, max_digits=20, null=True)),
                ('unique_squirrel_id', models.CharField(max_length=20, null=True)),
                ('hectare', models.CharField(max_length=15, null=True)),
                ('shift', models.CharField(max_length=10, null=True)),
                ('date', models.DateField()),
                ('hectare_squirrel_number', models.IntegerField()),
                ('age', models.CharField(max_length=10, null=True)),
                ('primary_fur_color', models.CharField(max_length=15, null=True)),
                ('highlight_fur_color', models.CharField(max_length=15, null=True)),
                ('combination_of_primary_and_highlight_color', models.CharField(max_length=100, null=True)),
                ('color_notes', models.CharField(max_length=200, null=True)),
                ('locatin', models.CharField(max_length=20, null=True)),
                ('above_ground_sighter_measurement', models.CharField(max_length=10, null=True)),
                ('specific_location', models.CharField(max_length=200, null=True)),
                ('running', models.BooleanField()),
                ('chasing', models.BooleanField()),
                ('climbing', models.BooleanField()),
                ('eating', models.BooleanField()),
                ('foraging', models.BooleanField()),
                ('other_activities', models.CharField(max_length=200, null=True)),
                ('kuks', models.BooleanField()),
                ('quaas', models.BooleanField()),
                ('moans', models.BooleanField()),
                ('tail_flags', models.BooleanField()),
                ('tail_twitches', models.BooleanField()),
                ('approaches', models.BooleanField()),
                ('indifferent', models.BooleanField()),
                ('runs_from', models.BooleanField()),
            ],
        ),
    ]
